import "./globals.css";
import { Sora } from "next/font/google";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/all-other/footer";
import Underfooter from "@/components/all-other/underfooter";
import CartProvider from "@/components/counter/QuantityContext";
import type { Metadata } from "next";
const sora = Sora({
  subsets: ["latin"],
});
export const metadata = {
  title: "Dine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <div className="mx-12 my-10  xl:mx-32 xl:my-16">
          <CartProvider>
            <Navbar />
            {children}
            <Footer />
            <Underfooter />
          </CartProvider>
        </div>
      </body>
    </html>
  );
}
