import "./globals.css";
import { Sora } from "next/font/google";
import type { Metadata } from "next";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
const sora = Sora({
  subsets: ["latin"],
});
export const metadata = {
  title: "Dine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <div className="mx-12 my-10  xl:mx-32 xl:my-16">
            <NavBar/>
            {children}
            <Footer/>
        </div>
      </body>
    </html>
  );
}
